# Generated by Django 3.2.7 on 2021-10-13 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='create',
            new_name='created',
        ),
    ]
